---
# tasks file for docker-compose | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and placing {{ dockercompose_app }} {{ dockercompose_version }} to {{ dockercompose_bin_path }}
  get_url:
    url: "{{ dockercompose_dl_url }}"
    dest: "{{ dockercompose_bin_path }}/{{ dockercompose_app }}"
    mode: "{{ dockercompose_file_mode }}"
