---
# tasks file for docker-compose

- name: Import install_debian.yml if OS family is Debian
  import_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Import install_el.yml if OS family is EL
  import_tasks: install_el.yml
  when: ansible_os_family == "RedHat"

- name: New Soft Link
  file:
    src: "{{ dockercompose_bin_path }}/{{ dockercompose_app }}"
    dest: "/usr/bin/{{ dockercompose_app }}"
    state: link
  become: yes
  become_method: sudo
